//VERSION FORMAT- BUILD_NUMBER-TIMESTAMP-GIT_SHA in nexus repo.
//Example:        41-20260611-120112-f405721

pipeline {
    agent any

    tools {
        maven "MAVEN3.9.9"
        jdk "JDK17"
    }

    environment {
        cluster = "vproappProd"
        service = "vprofileapptask-service-prod"
    }

    stages {

        stage('Deploy to Prod') {
            steps {
                withAWS(region: 'us-east-1', credentials: 'awscreds') {
                    sh """
                        aws ecs update-service \
                            --cluster ${cluster} \
                            --service ${service} \
                            --force-new-deployment
                    """
                }
            }
        }

    }

    post {

        success {
            echo "PIPELINE SUCCESS ✅"
        }

        failure {
            echo "PIPELINE FAILED ❌"
        }

        always {
            cleanWs(
                deleteDirs: true,
                disableDeferredWipeout: true
            )
        }
    }
}